/// Danh sách gợi ý tên thủ tục, chia theo nhóm.
class ProcedureSuggestions {
  static const Map<String, List<String>> groups = {
    '👤 Nhân thân': [
      'Giấy khai sinh',
      'Giấy khai tử',
      'CMND',
      'CMND mặt trước',
      'CMND mặt sau',
      'Căn cước công dân',
      'CCCD mặt trước',
      'CCCD mặt sau',
      'Hộ chiếu',
      'Sổ hộ khẩu',
      'Sổ tạm trú',
      'Giấy xác nhận thông tin cư trú',
      'Giấy đăng ký tạm trú',
      'Giấy đăng ký tạm vắng',
      'Giấy xác nhận độc thân',
      'Lý lịch tư pháp',
    ],
    '💑 Hôn nhân - Gia đình': [
      'Giấy đăng ký kết hôn',
      'Giấy xác nhận tình trạng hôn nhân',
      'Quyết định ly hôn',
      'Bản án ly hôn',
      'Giấy khai sinh con',
    ],
    '🏠 Nhà đất': [
      'Giấy chứng nhận quyền sử dụng đất',
      'Giấy chứng nhận quyền sở hữu nhà ở',
      'Giấy xác nhận nhà và đất ở hợp pháp',
      'Hợp đồng mua bán nhà đất',
      'Hợp đồng thuê nhà',
      'Hợp đồng mượn nhà',
      'Hợp đồng chuyển nhượng đất',
      'Hợp đồng tặng cho nhà đất',
      'Biên bản bàn giao nhà',
      'Biên bản bàn giao đất',
      'Trích lục bản đồ địa chính',
      'Trích sao hồ sơ địa chính',
      'Giấy nộp tiền sử dụng đất',
      'Biên lai thuế nhà đất',
      'Giấy tờ về quyền sở hữu tài sản gắn liền với đất',
    ],
    '✍️ Uỷ quyền - Thừa kế': [
      'Giấy uỷ quyền',
      'Hợp đồng uỷ quyền',
      'Văn bản uỷ quyền',
      'Di chúc',
      'Biên bản họp gia đình',
      'Văn bản thoả thuận phân chia di sản',
      'Văn bản khai nhận di sản',
    ],
    '💰 Tài chính - Ngân hàng': [
      'Sổ tiết kiệm',
      'Sao kê ngân hàng',
      'Giấy xác nhận số dư',
      'Hợp đồng vay vốn',
      'Hợp đồng tín dụng',
      'Giấy xác nhận thu nhập',
    ],
    '🏛️ Hành chính - Pháp lý': [
      'Đơn đề nghị',
      'Đơn xin',
      'Tờ khai đăng ký',
      'Giấy xác nhận của Công an',
      'Giấy xác nhận của UBND',
      'Giấy xác nhận cư trú',
      'Giấy xác nhận hộ nghèo',
      'Giấy xác nhận khuyết tật',
      'Giấy khám sức khoẻ',
    ],
    '🚗 Xe cộ': [
      'Đăng ký xe',
      'Giấy phép lái xe',
      'Bảo hiểm xe',
      'Hợp đồng mua bán xe',
      'Giấy chứng nhận kiểm định',
    ],
    '🎓 Học tập - Lao động': [
      'Bằng tốt nghiệp',
      'Bảng điểm',
      'Học bạ',
      'Hợp đồng lao động',
      'Sổ bảo hiểm xã hội',
      'Quyết định nghỉ việc',
      'Quyết định bổ nhiệm',
    ],
  };

  /// Danh sách phẳng tất cả tên — dùng cho tìm kiếm.
  static List<String> get all =>
      groups.values.expand((e) => e).toList();
}
